// Command validate checks the dataset: shape, references and provenance.
// Errors fail the build; "seed" rules are listed as warnings so contributors
// can pick one up.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/Wander-Kit/borderkit"
)

func main() {
	var d *borderkit.Dataset
	var err error
	seedMD := ""
	args := os.Args[1:]
	if len(args) >= 2 && args[0] == "-seed-md" {
		seedMD, args = args[1], args[2:]
	}
	if len(args) > 0 {
		d, err = borderkit.LoadFS(os.DirFS(args[0]), ".")
	} else {
		d, err = borderkit.Load()
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "load:", err)
		os.Exit(1)
	}
	msgs := d.Validate()
	errs, warns := 0, 0
	for _, m := range msgs {
		fmt.Println(m)
		if strings.HasPrefix(m, "E ") {
			errs++
		} else {
			warns++
		}
	}
	fmt.Printf("\n%d countries, %d groups, %d errors, %d rules still need a source\n", len(d.CountryCodes()), len(d.Groups), errs, warns)
	if seedMD != "" {
		if err := os.WriteFile(seedMD, []byte(seedMarkdown(msgs)), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "seed list:", err)
			os.Exit(1)
		}
	}
	if errs > 0 {
		os.Exit(1)
	}
}

// seedMarkdown renders the "needs a source" warnings as a checklist grouped by
// country, so contributors can pick one up (docs/SEED.md).
func seedMarkdown(msgs []string) string {
	byCountry := map[string][]string{}
	var order []string
	for _, m := range msgs {
		if !strings.HasPrefix(m, "W ") {
			continue
		}
		rest := strings.TrimPrefix(m, "W ")
		cc := strings.SplitN(rest, " ", 2)[0]
		if _, seen := byCountry[cc]; !seen {
			order = append(order, cc)
		}
		byCountry[cc] = append(byCountry[cc], rest)
	}
	var b strings.Builder
	b.WriteString("# Rules that still need a source\n\nGenerated by `go run ./cmd/validate -seed-md docs/SEED.md`. Each line is one rule migrated from a curated table with `confidence: seed`. To close one: find the official page, add `source`, set `verified` to today and `confidence` to high/medium/low, and open a pull request. See CONTRIBUTING.md.\n\n")
	fmt.Fprintf(&b, "%d rules across %d countries.\n\n", countWarnings(msgs), len(order))
	for _, cc := range order {
		fmt.Fprintf(&b, "## %s — `data/countries/%s.yaml`\n\n", cc, cc)
		for _, r := range byCountry[cc] {
			fmt.Fprintf(&b, "- [ ] %s\n", strings.TrimSuffix(strings.TrimSpace(strings.TrimPrefix(r, cc)), ": needs an official source (confidence seed)"))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func countWarnings(msgs []string) int {
	n := 0
	for _, m := range msgs {
		if strings.HasPrefix(m, "W ") {
			n++
		}
	}
	return n
}
